name: Greetings

on: [pull_request]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome to open-source community! Thanks so much for creating your first issue :)'
        pr-message: 'Thanks so much for creating your first PR, Best of luck for the hacktoberfest :)'
